// Repairs a known corruption in Claude Agent SDK session transcripts that
// permanently wedges a resumed chat when extended thinking is enabled.
//
// The corruption: the SDK occasionally persists several distinct model
// responses (each separated by a tool_result user message) under a single
// reused `message.id`. On the next resume the SDK groups assistant content
// blocks by `message.id`, so those responses collapse into ONE assistant
// message holding multiple `thinking` blocks at non-leading positions. The
// Anthropic API rejects that with:
//
//   400 messages.<n>.content.<m>: `thinking` or `redacted_thinking` blocks in
//   the latest assistant message cannot be modified. These blocks must remain
//   as they were in the original response.
//
// Because the bad message sits near the start of history it is replayed on
// every turn, so the chat fails identically forever.
//
// Per the Anthropic extended-thinking docs, a thinking block must be the FIRST
// content block of its message and "the entire sequence of consecutive thinking
// blocks must match the outputs generated by the model during the original
// request" — i.e. responses cannot be concatenated into one message. The fix is
// therefore to restore a unique `message.id` per model response so the SDK
// reconstructs each response as its own assistant message with its single
// leading thinking block.
//
// The repair only ever rewrites the inner `message.id` of assistant entries
// that share an id with an earlier response. It never touches the top-level
// `uuid`/`parentUuid` threading, tool_use ids, tool_result references, thinking
// text, or signatures (signatures are bound to the thinking content, not the
// message id), so it is safe and order-preserving.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";

export interface ClaudeTranscriptRepairResult {
  /** True when at least one reused message id was un-merged and the file rewritten. */
  repaired: boolean;
  /** Number of model responses that were given a fresh unique message id. */
  responsesRekeyed: number;
  /** Number of distinct message ids that were found shared across responses. */
  reusedMessageIds: number;
}

const NO_OP: ClaudeTranscriptRepairResult = {
  repaired: false,
  responsesRekeyed: 0,
  reusedMessageIds: 0,
};

const defaultMakeId = (): string => `msg_${randomUUID().replace(/-/g, "")}`;

/**
 * Pure transform over the raw JSONL lines of a Claude SDK transcript.
 *
 * Walks message entries in order. A "response" is a maximal run of consecutive
 * assistant entries uninterrupted by a user message (matching how the SDK
 * groups streamed blocks into one model response). If a `message.id` is reused
 * by a response after it was already used by an earlier one, every entry of the
 * later response is rewritten to a fresh unique id.
 *
 * Lines that are not changed are returned byte-for-byte unchanged, so a healthy
 * transcript round-trips identically (no write). Idempotent: running it on an
 * already-repaired transcript reports no change.
 */
export function repairClaudeTranscriptLines(
  lines: string[],
  makeId: () => string = defaultMakeId,
): { changed: boolean; lines: string[]; result: ClaudeTranscriptRepairResult } {
  const out = lines.slice();

  // Message ids already claimed by a response we've fully entered.
  const claimedIds = new Set<string>();
  const reusedIds = new Set<string>();
  let responsesRekeyed = 0;
  let changed = false;

  let insideAssistantRun = false;
  let runReplacementId: string | null = null;

  for (let i = 0; i < lines.length; i += 1) {
    const text = lines[i]?.trim();
    if (!text) continue;

    let obj: any;
    try {
      obj = JSON.parse(text);
    } catch {
      continue; // non-JSON line — leave untouched
    }

    const role: unknown = obj?.message?.role;
    // Only user/assistant message entries participate in turn structure.
    // Metadata lines (attachments, snapshots, queue ops, titles…) are ignored
    // and must not break or join an assistant run.
    if (role !== "assistant" && role !== "user") continue;

    if (role === "user") {
      insideAssistantRun = false;
      runReplacementId = null;
      continue;
    }

    // role === "assistant"
    const msgId: string | null = typeof obj.message?.id === "string" ? obj.message.id : null;

    if (!insideAssistantRun) {
      // First entry of a new model response.
      insideAssistantRun = true;
      if (msgId && claimedIds.has(msgId)) {
        // This id already belonged to an earlier response → collision. Mint a
        // fresh id for this whole response so it stays a separate message.
        runReplacementId = makeId();
        reusedIds.add(msgId);
        claimedIds.add(runReplacementId);
        responsesRekeyed += 1;
      } else {
        runReplacementId = null; // keep the original id (or absent id) as-is
        if (msgId) claimedIds.add(msgId);
      }
    }

    if (runReplacementId && obj.message && msgId !== runReplacementId) {
      obj.message.id = runReplacementId;
      out[i] = JSON.stringify(obj);
      changed = true;
    }
  }

  return {
    changed,
    lines: out,
    result: { repaired: changed, responsesRekeyed, reusedMessageIds: reusedIds.size },
  };
}

/**
 * Best-effort, synchronous repair of a transcript file on disk. Never throws;
 * returns a no-op result on any failure. Only writes when the content actually
 * changes, and keeps a one-time `<file>.corrupt.bak` snapshot of the first
 * corrupted state for forensics. Writes atomically via a temp file + rename.
 */
export function repairClaudeTranscriptFileSync(
  filePath: string,
  makeId: () => string = defaultMakeId,
): ClaudeTranscriptRepairResult {
  try {
    if (!filePath || !fs.existsSync(filePath)) return NO_OP;
    const raw = fs.readFileSync(filePath, "utf8");
    // Symmetric split/join preserves the exact line count and trailing newline.
    const { changed, lines, result } = repairClaudeTranscriptLines(raw.split("\n"), makeId);
    if (!changed) return NO_OP;

    const backup = `${filePath}.corrupt.bak`;
    if (!fs.existsSync(backup)) {
      try {
        fs.copyFileSync(filePath, backup);
      } catch {
        /* backup is best-effort */
      }
    }

    const tmp = `${filePath}.repair-${process.pid}-${randomUUID()}.tmp`;
    try {
      fs.writeFileSync(tmp, lines.join("\n"), "utf8");
      fs.renameSync(tmp, filePath);
    } catch (writeError) {
      // Don't leave a half-written temp file behind on failure.
      try {
        if (fs.existsSync(tmp)) fs.unlinkSync(tmp);
      } catch {
        /* ignore */
      }
      throw writeError;
    }
    return result;
  } catch {
    return NO_OP;
  }
}

/**
 * Resolve the on-disk path of a Claude Agent SDK session transcript.
 *
 * The SDK stores transcripts at `<config>/projects/<encoded-cwd>/<sessionId>.jsonl`
 * where `<config>` is `$CLAUDE_CONFIG_DIR` or `~/.claude` and `<encoded-cwd>` is
 * the absolute cwd with every non-alphanumeric character replaced by `-`. We try
 * that path first, then fall back to scanning the projects dir by filename so a
 * cwd-encoding drift can't defeat the lookup.
 */
export function resolveClaudeSdkTranscriptPath(
  sessionId: string | null | undefined,
  cwd: string | null | undefined,
): string | null {
  const id = typeof sessionId === "string" ? sessionId.trim() : "";
  if (!id) return null;
  // Session ids are UUID-like. Reject anything else so a malformed id can never
  // be interpolated into a path (e.g. "../") and target an unrelated file.
  if (!/^[A-Za-z0-9_-]+$/.test(id)) return null;

  const configDir = process.env.CLAUDE_CONFIG_DIR?.trim().length
    ? process.env.CLAUDE_CONFIG_DIR.trim()
    : path.join(os.homedir(), ".claude");
  const projectsDir = path.join(configDir, "projects");

  if (cwd && cwd.trim().length) {
    const slug = cwd.replace(/[^a-zA-Z0-9]/g, "-");
    const direct = path.join(projectsDir, slug, `${id}.jsonl`);
    if (fs.existsSync(direct)) return direct;
  }

  try {
    for (const entry of fs.readdirSync(projectsDir)) {
      const candidate = path.join(projectsDir, entry, `${id}.jsonl`);
      if (fs.existsSync(candidate)) return candidate;
    }
  } catch {
    /* projects dir missing — nothing to repair */
  }
  return null;
}

/** Resolve + repair a resume target. Best-effort; never throws. */
export function repairClaudeResumeTranscript(
  sessionId: string | null | undefined,
  cwd: string | null | undefined,
  makeId: () => string = defaultMakeId,
): ClaudeTranscriptRepairResult {
  const filePath = resolveClaudeSdkTranscriptPath(sessionId, cwd);
  if (!filePath) return NO_OP;
  return repairClaudeTranscriptFileSync(filePath, makeId);
}

/**
 * True when an error is the Anthropic 400 raised by replaying modified/merged
 * thinking blocks — the failure this module repairs.
 */
export function isCorruptThinkingTranscriptError(error: unknown): boolean {
  const message = (error instanceof Error ? error.message : String(error ?? "")).toLowerCase();
  return (
    message.includes("cannot be modified") &&
    (message.includes("thinking") || message.includes("redacted_thinking"))
  );
}
