/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ArtifactIndex": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Artifacts": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Blobs": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "CLERK_OAUTH_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Jobs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "JobsDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "JobsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Lanes": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Manifests": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Projects": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "RateLimits": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}