/**
 * PlanMarkdown — markdown renderer for the orchestration plan view.
 *
 * Sibling to ChatMarkdown but with richer behaviour tuned for plan.md content:
 *   • ```mermaid fences        → lazy-loaded mermaid diagram render
 *   • images (registered asset paths)
 *                              → embedded inline, max-width clamped
 *   • anchors pointing at      → spec preview card (sandboxed iframe thumbnail
 *     `artifacts/ui/*.html`      with a "View full design" button)
 *   • headings                 → stable `data-section-id="<slug>"` anchors,
 *                                generated by a local rehype-slug equivalent
 *                                (we don't ship the rehype-slug package).
 *
 * Engine: react-markdown + remark-gfm + rehype-raw (all installed). We
 * implement slug generation in a tiny visitor instead of pulling in
 * rehype-slug, and render mermaid via the installed `mermaid` package using
 * a lazy dynamic import (no remark-mermaid plugin needed).
 */

import {
  type CSSProperties,
  type ReactNode,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
} from "react";
import ReactMarkdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import rehypeSanitize, { defaultSchema, type Options as RehypeSanitizeOptions } from "rehype-sanitize";
import type { Root, Element as HastElement, Text as HastText } from "hast";
import { ArrowSquareOut, FileHtml } from "@phosphor-icons/react";
import { cn } from "../ui/cn";
import { openUrlInAdeBrowser } from "../../lib/openExternal";

export type PlanAssetResolver = (path: string) =>
  | { url: string; kind?: "image" | "html" | "other"; srcDoc?: string }
  | null
  | undefined;

export type PlanMarkdownProps = {
  source: string;
  /**
   * Resolves a relative path inside the orchestration bundle to a renderable
   * URL (typically `file://...` for HTML specs and screenshots). If null /
   * absent, the renderer falls back to the raw href / src — useful in tests.
   */
  resolveAsset?: PlanAssetResolver;
  /**
   * Bundle root (for "View full design" URL composition when the asset
   * resolver is not provided).
   */
  bundleRoot?: string | null;
  /** Optional click-anchor hook for tests / external coordination. */
  onSectionClick?: (sectionId: string) => void;
  className?: string;
};

const planSanitizeSchema: RehypeSanitizeOptions = {
  ...defaultSchema,
  tagNames: Array.from(new Set([...(defaultSchema.tagNames ?? []), "a", "sub", "details", "summary"])),
  attributes: {
    ...(defaultSchema.attributes ?? {}),
    "*": Array.from(new Set([...(defaultSchema.attributes?.["*"] ?? []), "id", "title"])),
    a: Array.from(new Set([...(defaultSchema.attributes?.a ?? []), "href", "id", "title"])),
    h1: Array.from(new Set([...(defaultSchema.attributes?.h1 ?? []), "id", "dataSectionId"])),
    h2: Array.from(new Set([...(defaultSchema.attributes?.h2 ?? []), "id", "dataSectionId"])),
    h3: Array.from(new Set([...(defaultSchema.attributes?.h3 ?? []), "id", "dataSectionId"])),
    h4: Array.from(new Set([...(defaultSchema.attributes?.h4 ?? []), "id", "dataSectionId"])),
    h5: Array.from(new Set([...(defaultSchema.attributes?.h5 ?? []), "id", "dataSectionId"])),
    h6: Array.from(new Set([...(defaultSchema.attributes?.h6 ?? []), "id", "dataSectionId"])),
  },
  clobber: (defaultSchema.clobber ?? []).filter((name) => name !== "id"),
};

/** Tags that participate in slug generation. */
const HEADING_TAGS = new Set(["h1", "h2", "h3", "h4", "h5", "h6"]);

function isElement(node: unknown): node is HastElement {
  return (
    typeof node === "object" &&
    node !== null &&
    (node as { type?: string }).type === "element"
  );
}

function isText(node: unknown): node is HastText {
  return (
    typeof node === "object" &&
    node !== null &&
    (node as { type?: string }).type === "text"
  );
}

function extractText(node: HastElement): string {
  let out = "";
  const walk = (n: HastElement["children"][number]): void => {
    if (isText(n)) {
      out += n.value;
      return;
    }
    if (isElement(n) && Array.isArray(n.children)) {
      for (const child of n.children) walk(child);
    }
  };
  for (const child of node.children) walk(child);
  return out;
}

/** Slug rule: lower-case, ASCII, dashed, dedupe with `-2`, `-3`, ... */
export function slugify(text: string, taken: Set<string>): string {
  const base =
    text
      .normalize("NFKD")
      .replace(/[̀-ͯ]/g, "")
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, "")
      .trim()
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-") || "section";
  let candidate = base;
  let i = 2;
  while (taken.has(candidate)) {
    candidate = `${base}-${i++}`;
  }
  taken.add(candidate);
  return candidate;
}

/**
 * Local rehype-slug equivalent. Walks the hast tree, assigns `id` and
 * `data-section-id` to every heading.
 */
function rehypeSectionAnchors() {
  return (tree: Root) => {
    const taken = new Set<string>();
    const visit = (node: Root | HastElement) => {
      const children = (node as HastElement).children ?? (tree as Root).children;
      for (const child of children) {
        if (!isElement(child)) continue;
        if (HEADING_TAGS.has(child.tagName)) {
          const text = extractText(child);
          const slug = slugify(text, taken);
          child.properties = {
            ...(child.properties ?? {}),
            id: slug,
            "data-section-id": slug,
          };
        }
        if (Array.isArray(child.children) && child.children.length > 0) {
          visit(child);
        }
      }
    };
    visit(tree);
  };
}

/* ──────────────────────────────────────────────────────────────────────────
   Mermaid block.
   We render a single `<MermaidBlock>` per fenced mermaid code; it lazily
   loads the `mermaid` package the first time it mounts. If the import fails
   (offline / not installed) we fall back to a `<pre>` with the original
   source so users still see something useful.
   ────────────────────────────────────────────────────────────────────────── */
type MermaidModule = { default: { initialize: (opts: object) => void; render: (id: string, src: string) => Promise<{ svg: string }>; } };

let mermaidPromise: Promise<MermaidModule> | null = null;
function loadMermaid(): Promise<MermaidModule> {
  if (mermaidPromise) return mermaidPromise;
  mermaidPromise = import("mermaid").then((mod) => {
    const m = mod as unknown as MermaidModule;
    try {
      m.default.initialize({
        startOnLoad: false,
        securityLevel: "strict",
        theme: "dark",
        fontFamily: "var(--font-mono)",
      });
    } catch {
      /* ignore: re-init is harmless */
    }
    return m;
  }).catch((err) => {
    mermaidPromise = null;
    throw err;
  });
  return mermaidPromise;
}

function MermaidBlock({ source }: { source: string }) {
  const renderId = useId().replace(/[:]/g, "_");
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    loadMermaid()
      .then((m) => m.default.render(`mermaid-${renderId}`, source))
      .then((res) => {
        if (cancelled) return;
        setSvg(res.svg);
      })
      .catch((err) => {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : String(err));
      });
    return () => {
      cancelled = true;
    };
  }, [renderId, source]);

  if (error) {
    return (
      <pre
        className="mb-3 overflow-auto rounded-md border border-amber-300/20 bg-amber-300/[0.04] p-3 font-mono text-[11px] text-amber-200/80"
        title={`Mermaid render error: ${error}`}
      >
        {source}
      </pre>
    );
  }
  if (svg == null) {
    return (
      <div
        className="mb-3 flex items-center justify-center rounded-md border border-white/[0.06] bg-white/[0.02] py-6 text-[10px] uppercase tracking-[0.16em] text-muted-fg/55"
        role="status"
      >
        Rendering diagram…
      </div>
    );
  }
  return (
    <div
      data-mermaid-block=""
      className="mb-3 overflow-auto rounded-md border border-white/[0.06] bg-white/[0.02] p-3"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}

/* ──────────────────────────────────────────────────────────────────────────
   Spec preview card. Rendered for anchors to `artifacts/ui/*.html`.
   ────────────────────────────────────────────────────────────────────────── */
function SpecPreviewCard({
  href,
  resolvedUrl,
  label,
}: {
  href: string;
  resolvedUrl: string | null;
  label: string;
}) {
  // We render the card with inline-block <span> elements to remain valid
  // when react-markdown places this inside a <p>. iframes and buttons are
  // both phrasing content, and <span>s with `display: flex` keep the
  // visual layout intact without breaking HTML nesting rules.
  const url = resolvedUrl ?? href;
  return (
    <span
      data-plan-spec-card={href}
      className="my-3 inline-flex max-w-full flex-col gap-2 rounded-lg border border-white/[0.08] bg-white/[0.03] p-2.5 shadow-[0_8px_24px_-12px_rgba(0,0,0,0.45)]"
      style={{ width: 260 }}
    >
      <span className="flex items-center gap-2 px-1 pt-0.5">
        <FileHtml size={12} weight="duotone" className="text-violet-200/85" />
        <span className="truncate font-mono text-[10px] text-fg/75" title={href}>
          {label}
        </span>
      </span>
      <span
        className="block overflow-hidden rounded-md border border-white/[0.06] bg-black/40"
        style={{ width: "100%", height: 180 }}
      >
        <iframe
          title={`Preview of ${href}`}
          src={url}
          sandbox=""
          className="block h-full w-full"
          style={{ border: 0, pointerEvents: "none" }}
          loading="lazy"
        />
      </span>
      <button
        type="button"
        onClick={(event) => {
          event.preventDefault();
          openUrlInAdeBrowser(url);
        }}
        className="inline-flex items-center justify-center gap-1.5 rounded-md border border-violet-300/25 bg-violet-300/10 px-2.5 py-1 font-sans text-[10.5px] font-medium text-violet-100 transition-colors hover:bg-violet-300/15"
      >
        <ArrowSquareOut size={11} weight="bold" />
        View full design
      </button>
    </span>
  );
}

/* ──────────────────────────────────────────────────────────────────────────
   Component overrides factory.
   ────────────────────────────────────────────────────────────────────────── */
function buildComponents({
  resolveAsset,
  bundleRoot,
  onSectionClick,
}: {
  resolveAsset?: PlanAssetResolver;
  bundleRoot?: string | null;
  onSectionClick?: (sectionId: string) => void;
}): Components {
  const headerStyle: CSSProperties = {
    color: "var(--color-fg)",
    fontFamily: "var(--font-sans)",
  };

  const renderHeading = (level: 1 | 2 | 3 | 4 | 5 | 6) => {
    const Component = (props: {
      children?: ReactNode;
      id?: string;
    }) => {
      const Tag = `h${level}` as const;
      const sizes = ["text-[15px]", "text-[14px]", "text-[12.5px]", "text-[11.5px]", "text-[11px]", "text-[11px]"];
      const trackings = ["tracking-tight", "tracking-tight", "tracking-tight", "tracking-tight", "tracking-tight", "tracking-tight"];
      const sectionId = typeof props.id === "string" ? props.id : undefined;
      return (
        <Tag
          id={sectionId}
          data-section-id={sectionId}
          className={cn(
            "mb-1.5 mt-3 font-semibold first:mt-0",
            sizes[level - 1],
            trackings[level - 1],
            "text-fg/85",
            onSectionClick ? "cursor-pointer" : undefined,
          )}
          style={headerStyle}
          onClick={
            onSectionClick && sectionId
              ? () => onSectionClick(sectionId)
              : undefined
          }
        >
          {props.children}
        </Tag>
      );
    };
    // react-markdown components props include extra fields; cast to satisfy
    // the heading-component signature without spelling out every prop.
    return Component as unknown as Components["h1"];
  };

  return {
    h1: renderHeading(1),
    h2: renderHeading(2),
    h3: renderHeading(3),
    h4: renderHeading(4),
    h5: renderHeading(5),
    h6: renderHeading(6),
    p: ({ children }) => (
      <p className="mb-2.5 leading-[1.55] text-[12.5px] text-fg/75 last:mb-0">{children}</p>
    ),
    ul: ({ children }) => (
      <ul className="mb-2.5 list-disc space-y-1 pl-5 text-[12.5px] text-fg/75 last:mb-0">{children}</ul>
    ),
    ol: ({ children }) => (
      <ol className="mb-2.5 list-decimal space-y-1 pl-5 text-[12.5px] text-fg/75 last:mb-0">{children}</ol>
    ),
    li: ({ children }) => <li className="leading-[1.5]">{children}</li>,
    hr: () => <hr className="my-3 border-white/[0.06]" />,
    blockquote: ({ children }) => (
      <blockquote className="mb-3 border-l-2 border-violet-300/30 bg-violet-300/[0.04] py-1 pl-3 text-[12px] text-fg/70 last:mb-0">
        {children}
      </blockquote>
    ),
    strong: ({ children }) => <strong className="font-semibold text-fg/95">{children}</strong>,
    em: ({ children }) => <em className="italic text-fg/85">{children}</em>,
    table: ({ children }) => (
      <div className="mb-3 max-w-full overflow-x-auto last:mb-0">
        <table className="w-full min-w-0 border-collapse text-left text-[11.5px]">{children}</table>
      </div>
    ),
    th: ({ children }) => (
      <th
        className="break-words px-2 py-1 font-semibold text-fg/80"
        style={{ border: "1px solid rgba(255,255,255,0.08)" }}
      >
        {children}
      </th>
    ),
    td: ({ children }) => (
      <td
        className="break-words px-2 py-1 align-top text-fg/70"
        style={{ border: "1px solid rgba(255,255,255,0.06)" }}
      >
        {children}
      </td>
    ),
    pre: ({ children }) => {
      // Inspect for a fenced mermaid block — react-markdown wraps the
      // <code class="language-mermaid"> inside a <pre>.
      const first = Array.isArray(children) ? children[0] : children;
      if (first && typeof first === "object" && "props" in (first as object)) {
        const props = (first as { props?: { className?: string; children?: ReactNode } }).props;
        const className = props?.className ?? "";
        const match = /language-([\w-]+)/.exec(className);
        if (match && match[1] === "mermaid") {
          let codeText = "";
          const walk = (n: ReactNode): void => {
            if (typeof n === "string" || typeof n === "number") {
              codeText += String(n);
            } else if (Array.isArray(n)) {
              n.forEach(walk);
            } else if (n && typeof n === "object" && "props" in (n as object)) {
              walk((n as { props: { children?: ReactNode } }).props.children);
            }
          };
          walk(props?.children);
          return <MermaidBlock source={codeText.trim()} />;
        }
      }
      return (
        <pre
          className="mb-3 overflow-auto rounded-md p-3 font-mono text-[11px] leading-[1.55]"
          style={{
            background: "rgba(255,255,255,0.025)",
            border: "1px solid rgba(255,255,255,0.06)",
          }}
        >
          {children}
        </pre>
      );
    },
    code: ({ children, className }) => {
      if (className && /language-/.test(className)) {
        return <code className={className}>{children}</code>;
      }
      return (
        <code
          className="rounded-sm px-1 py-0.5 font-mono text-[11px] text-fg/80"
          style={{ background: "rgba(255,255,255,0.05)" }}
        >
          {children}
        </code>
      );
    },
    a: ({ children, href, ...rest }) => {
      const hrefStr = typeof href === "string" ? href : "";
      const looksLikeHtmlAsset = /(^|\/)artifacts\/ui\/.+\.html?$/i.test(hrefStr);
      if (looksLikeHtmlAsset) {
        const resolved = resolveAsset?.(hrefStr) ?? null;
        const url =
          resolved?.url ??
          (bundleRoot ? `file://${bundleRoot.replace(/\/$/, "")}/${hrefStr.replace(/^\//, "")}` : null);
        const label = hrefStr.split("/").slice(-1)[0] ?? hrefStr;
        return <SpecPreviewCard href={hrefStr} resolvedUrl={url} label={label} />;
      }
      return (
        <a
          {...rest}
          href={hrefStr}
          target="_blank"
          rel="noopener noreferrer"
          className="text-violet-200/95 underline underline-offset-2 transition-colors hover:text-violet-100"
          onClick={(event) => {
            event.preventDefault();
            openUrlInAdeBrowser(hrefStr);
          }}
        >
          {children}
        </a>
      );
    },
    img: ({ src, alt }) => {
      const srcStr = typeof src === "string" ? src : "";
      const resolved = resolveAsset?.(srcStr) ?? null;
      const url = resolved?.url ?? srcStr;
      return (
        <img
          src={url}
          alt={alt ?? ""}
          className="my-3 max-w-full rounded-md border border-white/[0.06] bg-black/30"
          style={{ height: "auto", maxHeight: 360 }}
        />
      );
    },
  } satisfies Components;
}

export function PlanMarkdown({
  source,
  resolveAsset,
  bundleRoot,
  onSectionClick,
  className,
}: PlanMarkdownProps) {
  const components = useMemo(
    () => buildComponents({ resolveAsset, bundleRoot, onSectionClick }),
    [resolveAsset, bundleRoot, onSectionClick],
  );
  const rootRef = useRef<HTMLDivElement | null>(null);

  return (
    <div
      ref={rootRef}
      data-plan-markdown=""
      className={cn("min-w-0", className)}
      style={{ fontFamily: "var(--font-sans)" }}
    >
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        rehypePlugins={[rehypeRaw, [rehypeSanitize, planSanitizeSchema], rehypeSectionAnchors]}
        components={components}
      >
        {source}
      </ReactMarkdown>
    </div>
  );
}

export default PlanMarkdown;
