import type { SyncFileRequest, SyncRemoteCommandAction } from "./types";

export const MOBILE_SYNC_COMPATIBILITY_CONTRACT_VERSION = 1;

export const MOBILE_SYNC_REQUIRED_REMOTE_COMMAND_ACTIONS = [
  "lanes.presence.announce",
  "lanes.presence.release",
  "lanes.refreshSnapshots",
  "work.listSessions",
  "prs.refresh",
  "lanes.getDetail",
  "work.updateSessionMeta",
  "prs.getMobileSnapshot",
  "work.runQuickCommand",
  "work.startCliSession",
  "work.sendToSession",
  "work.stopRuntime",
  "processes.listDefinitions",
  "processes.listRuntime",
  "processes.start",
  "processes.stop",
  "processes.kill",
  "lanes.create",
  "lanes.createFromUnstaged",
  "lanes.importBranch",
  "lanes.createChild",
  "lanes.attach",
  "lanes.listUnregisteredWorktrees",
  "lanes.adoptAttached",
  "lanes.rename",
  "lanes.reparent",
  "lanes.updateAppearance",
  "lanes.archive",
  "lanes.unarchive",
  "lanes.delete",
  "lanes.listTemplates",
  "lanes.getDefaultTemplate",
  "lanes.getEnvStatus",
  "lanes.initEnv",
  "lanes.applyTemplate",
  "lanes.rebaseStart",
  "lanes.rebasePush",
  "lanes.rebaseRollback",
  "lanes.rebaseAbort",
  "lanes.dismissRebaseSuggestion",
  "lanes.deferRebaseSuggestion",
  "lanes.dismissAutoRebaseStatus",
  "git.listBranches",
  "git.checkoutBranch",
  "git.getChanges",
  "git.getFile",
  "git.getFileHistory",
  "files.writeTextAtomic",
  "git.stageFile",
  "git.stageAll",
  "git.unstageFile",
  "git.unstageAll",
  "git.discardFile",
  "git.restoreStagedFile",
  "git.commit",
  "git.generateCommitMessage",
  "git.listRecentCommits",
  "git.listCommitFiles",
  "git.getCommitMessage",
  "git.isCommitInLaneHistory",
  "git.revertCommit",
  "git.cherryPickCommit",
  "git.createTag",
  "git.resetToCommit",
  "git.stashPush",
  "git.stashList",
  "git.stashApply",
  "git.stashPop",
  "git.stashDrop",
  "git.fetch",
  "git.pull",
  "git.undoLastHeadChange",
  "git.redoLastHeadChange",
  "git.getSyncStatus",
  "git.sync",
  "git.push",
  "git.getConflictState",
  "git.rebaseContinue",
  "git.rebaseAbort",
  "git.mergeContinue",
  "git.mergeAbort",
  "chat.models",
  "chat.modelCatalog",
  "chat.listSessions",
  "chat.create",
  "chat.launch",
  "chat.getSummary",
  "chat.getTranscript",
  "chat.getChatEventHistory",
  "chat.send",
  "chat.interrupt",
  "chat.steer",
  "chat.cancelSteer",
  "chat.editSteer",
  "chat.dispatchSteer",
  "chat.cancelDispatchedSteer",
  "chat.approve",
  "chat.respondToInput",
  "chat.updateSession",
  "cto.ensureSession",
  "cto.getLinearQuickView",
  "cto.getLinearIssuePickerData",
  "cto.searchLinearIssues",
  "cto.getLinearIssueComments",
  "prs.getForLane",
  "prs.createFromLane",
  "prs.createQueue",
  "prs.land",
  "prs.close",
  "prs.reopen",
  "prs.requestReviewers",
  "prs.draftDescription",
  "prs.rerunChecks",
  "prs.addComment",
  "prs.updateTitle",
  "prs.updateBody",
  "prs.setLabels",
  "prs.submitReview",
  "prs.replyToReviewThread",
  "prs.setReviewThreadResolved",
  "prs.reactToComment",
  "prs.aiReviewSummary",
  "prs.simulateIntegration",
  "prs.commitIntegration",
  "prs.listIntegrationWorkflows",
  "prs.updateIntegrationProposal",
  "prs.deleteIntegrationProposal",
  "prs.dismissIntegrationCleanup",
  "prs.cleanupIntegrationWorkflow",
  "prs.createIntegrationLaneForProposal",
  "prs.startIntegrationResolution",
  "prs.recheckIntegrationStep",
  "prs.landQueueNext",
  "prs.startQueueAutomation",
  "prs.pauseQueueAutomation",
  "prs.resumeQueueAutomation",
  "prs.cancelQueueAutomation",
  "prs.reorderQueue",
  "prs.getGitHubSnapshot",
  "prs.getReviewThreads",
  "prs.getActionRuns",
  "prs.getActivity",
  "prs.getDeployments",
  "deeplinks.open",
] as const satisfies readonly SyncRemoteCommandAction[];

export const MOBILE_SYNC_REQUIRED_FILE_REQUEST_ACTIONS = [
  "listWorkspaces",
  "readFile",
  "writeText",
  "createFile",
  "createDirectory",
  "rename",
  "deletePath",
  "quickOpen",
  "searchText",
  "listTree",
  "readArtifact",
] as const satisfies readonly SyncFileRequest["action"][];

export function evaluateMobileSyncCompatibility(
  actions: Iterable<string>,
): { mode: "full" | "limited"; missingActions: string[] } {
  const available = new Set(actions);
  const missingActions = MOBILE_SYNC_REQUIRED_REMOTE_COMMAND_ACTIONS
    .filter((action) => !available.has(action));
  return {
    mode: missingActions.length === 0 ? "full" : "limited",
    missingActions,
  };
}
