import { createHash, randomUUID } from "node:crypto";
import fsSync from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";

import type { HomeClipboardEntry, HomeClipboardImage, HomeClipboardState } from "../../../shared/types/homeWidgets";

/**
 * Clipboard history for the home page's Clipboard widget.
 *
 * Polls `clipboard.readText()` and `availableFormats()` once a second while
 * the watch is on (the widget is in the active home layout and not paused or
 * hidden). Both are tens of microseconds; a slow read (a huge copy) backs the
 * poll off. An image is read (≈5 ms for a 1440p screenshot) only when it
 * changed: the PNG copy apps put beside it is compared first (≈0.03 ms), and
 * an image with no PNG copy (Print Screen) is re-read at most every few
 * seconds.
 *
 * Privacy: copies a password manager marks as concealed and copies that look
 * like secrets are never kept. With "Keep after restart" off nothing is on
 * disk: turning it off, clearing, or removing an entry reaches the disk at
 * once, and a launch with it off removes what a crash may have left.
 */

/** An image on the clipboard, read once, with what the history needs from it. */
export type HomeClipboardImageRead = {
  width: number;
  height: number;
  /** Raw pixels, for the content hash. */
  bitmap: () => Buffer;
  /** The whole image as PNG (the encode costs ~15 ms for 1440p; called once per new image). */
  png: () => Buffer;
  /** A copy whose long side is at most `maxPx`, as PNG or JPEG bytes. */
  thumbnail: (maxPx: number) => { mime: "image/png" | "image/jpeg"; data: Buffer };
};

export type HomeWidgetsClipboard = {
  readText: () => string;
  writeText: (text: string) => void;
  readBuffer: (format: string) => Buffer;
  /** Whether a format is on the clipboard at all, even with no data (Electron's `clipboard.has`). */
  has?: (format: string) => boolean;
  availableFormats?: () => string[];
  /** Null when the clipboard has no image (or it is empty). */
  readImage?: () => HomeClipboardImageRead | null;
  writeImage?: (png: Buffer) => boolean;
};

type Logger = { warn: (event: string, data?: Record<string, unknown>) => void };

const CLIPBOARD_MAX_ENTRIES = 50;
const CLIPBOARD_MAX_CHARS = 20_000;
const CLIPBOARD_POLL_MS = 1_000;
const CLIPBOARD_SLOW_POLL_MS = 3_000;
/** A read slower than this (a multi-megabyte copy) moves the poll to the slow interval. */
const CLIPBOARD_SLOW_READ_MS = 8;
/** Full images kept for copying back, in memory (and on disk when kept): oldest go first. */
const CLIPBOARD_IMAGE_BYTES_CAP = 50 * 1024 * 1024;
const CLIPBOARD_MAX_IMAGES = 30;
const CLIPBOARD_THUMB_PX = 320;
/** How long added copies wait before the kept history is written (a burst of copies is one write). */
const CLIPBOARD_WRITE_DEBOUNCE_MS = 1_500;
/**
 * An image with no PNG copy beside it (Print Screen) can only be compared by
 * reading it (~7 ms for 1440p): re-read 3 s after a change, backing off to
 * every 12 s while it stays the same.
 */
const CLIPBOARD_IMAGE_REREAD_MS = 3_000;
const CLIPBOARD_IMAGE_REREAD_MAX_MS = 12_000;
/** The PNG format apps put beside a bitmap: Windows' registered "PNG", macOS' UTI. */
const PNG_CLIPBOARD_FORMAT: Partial<Record<NodeJS.Platform, string>> = { win32: "PNG", darwin: "public.png" };

/**
 * Formats a password manager puts on the clipboard to say "do not record
 * this". Their presence is the signal; most carry no data at all.
 * - Windows: the clipboard-history opt-out
 *   (`ExcludeClipboardContentFromMonitorProcessing`) and KeePass' "Clipboard
 *   Viewer Ignore".
 * - macOS: the nspasteboard.org markers.
 */
const CONCEALED_MARKER_FORMATS: Partial<Record<NodeJS.Platform, string[]>> = {
  win32: ["ExcludeClipboardContentFromMonitorProcessing", "Clipboard Viewer Ignore"],
  darwin: ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"],
};
/** Windows' `CanIncludeInClipboardHistory` is a DWORD: present and 0 means "keep out"; 1 means allowed. */
const WINDOWS_HISTORY_DWORD_FORMAT = "CanIncludeInClipboardHistory";

/** True when a password manager marked what is on the clipboard as not to be recorded. */
export function isConcealedClipboard(clipboard: HomeWidgetsClipboard, platform: NodeJS.Platform): boolean {
  for (const format of CONCEALED_MARKER_FORMATS[platform] ?? []) {
    try {
      if (clipboard.has) {
        if (clipboard.has(format)) return true;
      } else if (clipboard.readBuffer(format)?.length > 0) {
        return true;
      }
    } catch {
      // A format the platform cannot name is simply absent.
    }
  }
  if (platform === "win32") {
    try {
      const buffer = clipboard.readBuffer(WINDOWS_HISTORY_DWORD_FORMAT);
      if (buffer && buffer.length >= 4 && buffer.readUInt32LE(0) === 0) return true;
    } catch {
      // Absent.
    }
  }
  return false;
}

const SECRET_PATTERNS: RegExp[] = [
  /-----BEGIN [A-Z ]*PRIVATE KEY-----/,
  /\b(?:sk|pk|rk)-(?:ant-|proj-|live_|test_)?[A-Za-z0-9_-]{20,}/,
  /\b(?:sk|pk|rk)_(?:live|test)_[A-Za-z0-9]{16,}/,
  /\bgh[pousr]_[A-Za-z0-9]{30,}/,
  /\bgithub_pat_[A-Za-z0-9_]{40,}/,
  /\bglpat-[A-Za-z0-9_-]{20,}/,
  /\bxox[abprs]-[A-Za-z0-9-]{10,}/,
  /\bAKIA[0-9A-Z]{16}\b/,
  /\bAIza[0-9A-Za-z_-]{35}\b/,
  /\bya29\.[A-Za-z0-9_-]{20,}/,
  /\bhf_[A-Za-z0-9]{30,}/,
  /\bSG\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}/,
  /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/,
  /\blin_(?:api|oauth)_[A-Za-z0-9]{30,}/,
  /\bnpm_[A-Za-z0-9]{36}\b/,
];

/**
 * `password = "…"`, `API_KEY=…`, `"client_secret": "…"`: a secret-named key
 * given a value that looks like a literal. A quoted value of 8+ characters
 * counts unless it is a placeholder (`"${TOKEN}"`, `"<your key>"`); an
 * unquoted one must carry a digit and must not be a reference
 * (`token = getToken();`, `secret: process.env.SECRET`, `password: string`).
 */
const SECRET_ASSIGNMENT = /\b[\w-]*(?:password|passwd|secret|api[_-]?key|access[_-]?key|token)[\w-]*["']?\s*[:=]\s*(?:(["'`])([^"'`\s]{8,})\1|([^\s"'`;,(){}[\]]{8,})(?=$|[\s;,]))/gi;
const PLACEHOLDER_VALUE = /^(?:\$|<|%|\{)/;
const DOTTED_REFERENCE = /^[A-Za-z_$][\w$]*(?:\.[A-Za-z_$][\w$]*)+$/;

function hasSecretAssignment(text: string): boolean {
  for (const match of text.matchAll(SECRET_ASSIGNMENT)) {
    const quoted = match[2];
    if (quoted) {
      if (!PLACEHOLDER_VALUE.test(quoted)) return true;
      continue;
    }
    const bare = match[3] ?? "";
    if (/\d/.test(bare) && !PLACEHOLDER_VALUE.test(bare) && !DOTTED_REFERENCE.test(bare)) return true;
  }
  return false;
}

/** Shapes that mix every character class without being a secret: links, paths, addresses, package specs. */
const NOT_A_SECRET: RegExp[] = [
  /^(?:https?|ftp|ssh|git|file|wss?):\/\//i,
  /^[a-z]:[\\/]/i,
  /^\\\\[^\\]+\\/,
  /^(?:\/|~\/|\.{1,2}[\\/])/,
  // host.tld[:port][/path] with no scheme
  /^(?:[a-z0-9-]+\.)+[a-z]{2,24}(?::\d{1,5})?(?:[/?#]\S*)?$/i,
  // name@host.tld
  /^[\w.+-]+@(?:[a-z0-9-]+\.)+[a-z]{2,24}$/i,
  // dir/dir/file.ext or a/b/c
  /^[\w.@-]+(?:[\\/][\w.@-]+)+\.[A-Za-z0-9]{1,8}$/,
  /^(?:[\w.@-]+[\\/]){2,}[\w.@-]*$/,
  // @scope/name@1.2.3, name@^1.2.3
  /^(?:@[\w.-]+\/)?[\w.-]+@[\w.^~<>=*|-]+$/,
];

function shannonBitsPerChar(text: string): number {
  const counts = new Map<string, number>();
  for (const char of text) counts.set(char, (counts.get(char) ?? 0) + 1);
  let bits = 0;
  for (const count of counts.values()) {
    const p = count / text.length;
    bits -= p * Math.log2(p);
  }
  return bits;
}

/**
 * True for a copy that should not be kept: a known token shape, a private key,
 * a secret-named key with a literal value, or a lone high-entropy string that
 * mixes letters, digits and symbols the way generated passwords do. Hashes
 * and ids (hex, base32) pass, because they use fewer character classes.
 */
export function looksLikeSecret(text: string): boolean {
  const trimmed = text.trim();
  if (!trimmed) return false;
  if (SECRET_PATTERNS.some((pattern) => pattern.test(trimmed))) return true;
  if (hasSecretAssignment(trimmed)) return true;
  if (/\s/.test(trimmed) || trimmed.length < 12 || trimmed.length > 128) return false;
  // A link or a path mixes every character class too; a token inside one was caught above.
  if (NOT_A_SECRET.some((pattern) => pattern.test(trimmed))) return false;
  const classes = [/[a-z]/, /[A-Z]/, /[0-9]/, /[^A-Za-z0-9]/].filter((re) => re.test(trimmed)).length;
  return classes >= 4 && shannonBitsPerChar(trimmed) >= 3.5;
}

export function createClipboardHistory(deps: {
  dir: string;
  clipboard: HomeWidgetsClipboard;
  platform: NodeJS.Platform;
  broadcast: (state: HomeClipboardState) => void;
  logger?: Logger;
}) {
  const { platform } = deps;
  const dir = deps.dir;
  const settingsPath = path.join(dir, "settings.json");
  const historyPath = path.join(dir, "clipboard-history.json");
  const imagesDir = path.join(dir, "clipboard-images");
  const pngFormat = PNG_CLIPBOARD_FORMAT[platform] ?? null;

  let clipboardEnabled = false;
  let clipboardPersist = false;
  let entries: HomeClipboardEntry[] = [];
  let skippedSecrets = 0;
  /** What the last poll saw: "t:<text>", "i:<image key>" or "" for nothing. Null before the first poll. */
  let lastSeen: string | null = null;
  let lastFormats = "";
  /** When an image with no PNG copy was last read, and how long until the next look. */
  let lastImageReadAt = 0;
  let imageRereadWait = CLIPBOARD_IMAGE_REREAD_MS;
  /** Full PNGs of image entries, by hash. A kept history reads the rest from disk on copy. */
  const fullImages = new Map<string, Buffer>();
  let pollTimer: NodeJS.Timeout | null = null;
  let pollInterval = CLIPBOARD_POLL_MS;
  let writeTimer: NodeJS.Timeout | null = null;
  /** Disk work runs one at a time, in order, so a removal never races an older write. */
  let diskQueue: Promise<void> = Promise.resolve();
  let loaded: Promise<void> | null = null;

  const state = (): HomeClipboardState => ({
    enabled: clipboardEnabled,
    persist: clipboardPersist,
    entries,
    skippedSecrets,
  });

  const announce = () => deps.broadcast(state());

  const saveSettings = async () => {
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(settingsPath, JSON.stringify({ clipboard: { enabled: clipboardEnabled, persist: clipboardPersist } }));
  };

  const imageFile = (hash: string) => path.join(imagesDir, `${hash}.png`);

  /** Writes the history and the image files it names, and removes image files it no longer names. */
  const writeHistory = async () => {
    await fs.mkdir(imagesDir, { recursive: true });
    const wanted = new Set(entries.flatMap((entry) => (entry.image ? [`${entry.image.hash}.png`] : [])));
    for (const entry of entries) {
      if (!entry.image) continue;
      const full = fullImages.get(entry.image.hash);
      if (!full) continue;
      const file = imageFile(entry.image.hash);
      const exists = await fs.stat(file).then(() => true, () => false);
      if (!exists) await fs.writeFile(file, full);
    }
    for (const name of await fs.readdir(imagesDir).catch(() => [] as string[])) {
      if (!wanted.has(name)) await fs.rm(path.join(imagesDir, name), { force: true });
    }
    await fs.writeFile(historyPath, JSON.stringify(entries));
  };

  const removeHistoryFiles = () =>
    Promise.all([fs.rm(historyPath, { force: true }), fs.rm(imagesDir, { recursive: true, force: true })]).then(() => {});

  /** Brings the disk in line with memory now: the kept history, or nothing when it is not kept. */
  const syncDisk = (): Promise<void> => {
    if (writeTimer) clearTimeout(writeTimer);
    writeTimer = null;
    const task = diskQueue.then(() => (clipboardPersist ? writeHistory() : removeHistoryFiles()));
    diskQueue = task.catch((error: unknown) => deps.logger?.warn("home.clipboard.persist_failed", { error: String(error) }));
    return diskQueue;
  };

  /** New copies only: a burst of them is one write. Deletions use `syncDisk` directly. */
  const scheduleHistoryWrite = () => {
    if (writeTimer) clearTimeout(writeTimer);
    writeTimer = setTimeout(() => {
      writeTimer = null;
      void syncDisk();
    }, CLIPBOARD_WRITE_DEBOUNCE_MS);
    writeTimer.unref?.();
  };

  /** At quit: a write still waiting on its debounce lands synchronously (the loop will not run again). */
  const flushPendingWriteSync = () => {
    if (!writeTimer) return;
    clearTimeout(writeTimer);
    writeTimer = null;
    if (!clipboardPersist) return;
    try {
      fsSync.mkdirSync(imagesDir, { recursive: true });
      for (const entry of entries) {
        const full = entry.image ? fullImages.get(entry.image.hash) : null;
        if (!entry.image || !full) continue;
        const file = imageFile(entry.image.hash);
        if (!fsSync.existsSync(file)) fsSync.writeFileSync(file, full);
      }
      fsSync.writeFileSync(historyPath, JSON.stringify(entries));
    } catch (error) {
      deps.logger?.warn("home.clipboard.persist_failed", { error: String(error) });
    }
  };

  const isConcealed = () => isConcealedClipboard(deps.clipboard, platform);

  /**
   * Puts `entry` first and drops what is over the caps: 50 entries, and at
   * most 30 pictures and 50 MB of full images (the oldest pictures go first).
   */
  const pushEntry = (entry: HomeClipboardEntry, replacing: number) => {
    let images = 0;
    let imageBytes = 0;
    entries = [entry, ...entries.filter((_, index) => index !== replacing)]
      .slice(0, CLIPBOARD_MAX_ENTRIES)
      .filter((candidate) => {
        if (!candidate.image) return true;
        images += 1;
        imageBytes += candidate.image.bytes;
        return candidate === entry || (images <= CLIPBOARD_MAX_IMAGES && imageBytes <= CLIPBOARD_IMAGE_BYTES_CAP);
      });
    const kept = new Set(entries.flatMap((candidate) => (candidate.image ? [candidate.image.hash] : [])));
    for (const hash of [...fullImages.keys()]) if (!kept.has(hash)) fullImages.delete(hash);
    announce();
    if (clipboardPersist) scheduleHistoryWrite();
  };

  /** A cheap identity for the PNG copy on the clipboard: its length and a hash of its two ends. */
  const pngProbe = (): { key: string; png: Buffer } | null => {
    if (!pngFormat) return null;
    let png: Buffer;
    try {
      png = deps.clipboard.readBuffer(pngFormat);
    } catch {
      return null;
    }
    if (!png || png.length < 8) return null;
    const edge = 64 * 1024;
    const hash = createHash("sha1").update(png.subarray(0, edge));
    if (png.length > edge) hash.update(png.subarray(Math.max(edge, png.length - edge)));
    return { key: `png:${png.length}:${hash.digest("hex")}`, png };
  };

  /** A cheap identity for pixels: their size and 512 samples spread over the bitmap. */
  const pixelSample = (bitmap: Buffer, width: number, height: number) => {
    const hash = createHash("sha1").update(`${width}x${height}:`);
    const step = Math.max(64, Math.floor(bitmap.length / 512));
    for (let offset = 0; offset < bitmap.length; offset += step) hash.update(bitmap.subarray(offset, offset + 64));
    return hash.digest("hex");
  };

  const pixelHash = (read: HomeClipboardImageRead) =>
    createHash("sha1").update(`${read.width}x${read.height}:`).update(read.bitmap()).digest("hex");

  const recordImage = (read: HomeClipboardImageRead, hash: string, pngCopy: Buffer | null) => {
    const existing = entries.findIndex((entry) => entry.image?.hash === hash);
    if (existing >= 0) {
      pushEntry({ ...entries[existing]!, copiedAt: Date.now() }, existing);
      return;
    }
    const full = pngCopy ?? read.png();
    // One picture bigger than the whole budget is not kept.
    if (full.length === 0 || full.length > CLIPBOARD_IMAGE_BYTES_CAP) return;
    const thumb = read.thumbnail(CLIPBOARD_THUMB_PX);
    const image: HomeClipboardImage = {
      thumb: `data:${thumb.mime};base64,${thumb.data.toString("base64")}`,
      width: read.width,
      height: read.height,
      bytes: full.length,
      hash,
    };
    fullImages.set(hash, full);
    pushEntry({ id: randomUUID(), text: "", image, copiedAt: Date.now(), length: 0 }, -1);
  };

  const recordText = (text: string) => {
    if (isConcealed() || looksLikeSecret(text)) {
      skippedSecrets += 1;
      announce();
      return;
    }
    const kept = text.slice(0, CLIPBOARD_MAX_CHARS);
    const existing = entries.findIndex((entry) => !entry.image && entry.text === kept);
    const entry: HomeClipboardEntry = existing >= 0
      ? { ...entries[existing]!, copiedAt: Date.now() }
      : { id: randomUUID(), text: kept, copiedAt: Date.now(), length: text.length };
    pushEntry(entry, existing);
  };

  const poll = () => {
    const started = performance.now();
    let text: string;
    let formats: string[];
    try {
      text = deps.clipboard.readText() ?? "";
      formats = deps.clipboard.availableFormats?.() ?? [];
    } catch {
      return;
    }
    const elapsed = performance.now() - started;
    const nextInterval = elapsed > CLIPBOARD_SLOW_READ_MS ? CLIPBOARD_SLOW_POLL_MS : CLIPBOARD_POLL_MS;
    if (nextInterval !== pollInterval) restartPoll(nextInterval);
    const formatKey = formats.join("|");
    const formatsChanged = formatKey !== lastFormats;
    lastFormats = formatKey;
    const first = lastSeen == null;
    // The first read is what was on the clipboard before ADE looked; it is
    // recorded only when the history is empty, so a relaunch does not re-add it.
    const skipFirst = first && entries.length > 0;

    // Text wins: a spreadsheet or document copy also carries a picture of itself.
    const imageOnly = !text.trim() && deps.clipboard.readImage != null && formats.some((format) => format.startsWith("image/"));
    if (!imageOnly) {
      const seen = text.trim() ? `t:${text}` : "";
      if (seen === lastSeen) return;
      lastSeen = seen;
      if (seen && !skipFirst) recordText(text);
      return;
    }

    // An image. With a PNG copy beside it, compare that (cheap) and read the picture only when it changed.
    const probe = pngProbe();
    if (probe) {
      const seen = `i:${probe.key}`;
      if (seen === lastSeen) return;
      lastSeen = seen;
      if (skipFirst) return;
    } else {
      // No PNG copy (Print Screen, Paint): re-read the picture now and then, at once when the formats changed.
      if (!first && !formatsChanged && lastSeen?.startsWith("i:") && Date.now() - lastImageReadAt < imageRereadWait) return;
    }
    let read: HomeClipboardImageRead | null = null;
    try {
      read = deps.clipboard.readImage?.() ?? null;
    } catch {
      read = null;
    }
    lastImageReadAt = Date.now();
    if (!read) {
      if (!probe) lastSeen = "";
      return;
    }
    if (!probe) {
      const seen = `i:bmp:${pixelSample(read.bitmap(), read.width, read.height)}`;
      if (seen === lastSeen) {
        imageRereadWait = Math.min(CLIPBOARD_IMAGE_REREAD_MAX_MS, imageRereadWait * 2);
        return;
      }
      imageRereadWait = CLIPBOARD_IMAGE_REREAD_MS;
      lastSeen = seen;
      if (skipFirst) return;
    }
    if (isConcealed()) {
      skippedSecrets += 1;
      announce();
      return;
    }
    recordImage(read, pixelHash(read), probe?.png ?? null);
  };

  function restartPoll(interval: number) {
    if (pollTimer) clearInterval(pollTimer);
    pollInterval = interval;
    pollTimer = setInterval(poll, interval);
    pollTimer.unref?.();
  }

  const startPolling = () => {
    if (pollTimer) return;
    lastSeen = null;
    restartPoll(CLIPBOARD_POLL_MS);
    poll();
  };

  const stopPolling = () => {
    if (pollTimer) clearInterval(pollTimer);
    pollTimer = null;
    lastSeen = null;
  };

  /**
   * Where each window's grid has the Clipboard widget: on screen, or hidden
   * for lack of room. A window with no opinion (no home page, no Clipboard
   * widget) is absent. The watch runs while the saved switch is on and some
   * window shows the widget, or no window hides it (the home page is not open
   * anywhere): one window that hides it cannot stop another's.
   */
  const presence = new Map<number, "shown" | "hidden">();
  const shouldPoll = () => {
    if (!clipboardEnabled) return false;
    const views = [...presence.values()];
    return views.includes("shown") || !views.includes("hidden");
  };
  const syncPolling = () => {
    if (shouldPoll()) startPolling();
    else stopPolling();
  };

  const validImage = (value: unknown): value is HomeClipboardImage => {
    const image = value as HomeClipboardImage | null;
    return image != null && typeof image.thumb === "string" && image.thumb.startsWith("data:image/")
      && typeof image.hash === "string" && /^[0-9a-f]{40}$/.test(image.hash)
      && typeof image.width === "number" && typeof image.height === "number" && typeof image.bytes === "number";
  };

  /** Reads the saved switches (and history, when kept) once; later calls share the read. */
  const load = (): Promise<void> => {
    loaded ??= (async () => {
      try {
        const raw = JSON.parse(await fs.readFile(settingsPath, "utf8")) as { clipboard?: { enabled?: unknown; persist?: unknown } };
        clipboardEnabled = raw.clipboard?.enabled === true;
        clipboardPersist = raw.clipboard?.persist === true;
      } catch {
        // No settings yet: everything off.
      }
      if (clipboardPersist) {
        try {
          const saved = JSON.parse(await fs.readFile(historyPath, "utf8")) as unknown;
          if (Array.isArray(saved)) {
            entries = saved
              .filter((entry): entry is HomeClipboardEntry =>
                entry != null && typeof entry.id === "string" && typeof entry.text === "string" && typeof entry.copiedAt === "number"
                && (entry.image === undefined || validImage(entry.image)))
              .slice(0, CLIPBOARD_MAX_ENTRIES)
              .map((entry) => ({ ...entry, length: typeof entry.length === "number" ? entry.length : entry.text.length }));
          }
        } catch {
          // Missing or unreadable history starts empty.
        }
      } else {
        // Not kept: a history left by a crash (or an older build) does not stay on disk.
        await removeHistoryFiles().catch((error: unknown) => deps.logger?.warn("home.clipboard.persist_failed", { error: String(error) }));
      }
      syncPolling();
    })();
    return loaded;
  };

  return {
    load,
    getState: async () => {
      await load();
      return state();
    },
    configure: async (args: { enabled?: boolean; persist?: boolean }) => {
      await load();
      if (typeof args?.enabled === "boolean" && args.enabled !== clipboardEnabled) {
        clipboardEnabled = args.enabled;
        syncPolling();
      }
      if (typeof args?.persist === "boolean" && args.persist !== clipboardPersist) {
        clipboardPersist = args.persist;
        // Off: the files go now. On: what is in memory is written now.
        await syncDisk();
      }
      await saveSettings().catch((error: unknown) => deps.logger?.warn("home.clipboard.settings_failed", { error: String(error) }));
      announce();
      return state();
    },
    /** One window's view of the widget; null when it has none (closed, reloaded, no widget). */
    setPresence: async (windowId: number, view: "shown" | "hidden" | null) => {
      await load();
      if (view) presence.set(windowId, view);
      else presence.delete(windowId);
      syncPolling();
    },
    clear: async () => {
      await load();
      entries = [];
      fullImages.clear();
      skippedSecrets = 0;
      await syncDisk();
      announce();
      return state();
    },
    remove: async (id: string) => {
      await load();
      const removed = entries.find((entry) => entry.id === id);
      entries = entries.filter((entry) => entry.id !== id);
      if (removed?.image) fullImages.delete(removed.image.hash);
      if (removed && clipboardPersist) await syncDisk();
      announce();
      return state();
    },
    copy: async (id: string) => {
      const entry = entries.find((candidate) => candidate.id === id);
      if (!entry) return false;
      if (!entry.image) {
        deps.clipboard.writeText(entry.text);
        return true;
      }
      const full = fullImages.get(entry.image.hash)
        ?? await fs.readFile(imageFile(entry.image.hash)).catch(() => null);
      return Boolean(full && deps.clipboard.writeImage?.(full));
    },
    dispose: () => {
      stopPolling();
      flushPendingWriteSync();
    },
  };
}

export type ClipboardHistory = ReturnType<typeof createClipboardHistory>;
