// ---------------------------------------------------------------------------
// Which flags take a following value, and where a command's first real word is.
//
// Its own module because three readers need the same answer and one of them —
// `commands/plugin.ts`, which routes a plugin alias — is imported BY `cli.ts`.
// A shared fact that both a command and its dispatcher must agree on cannot
// live in either of them.
// ---------------------------------------------------------------------------

export const VALUE_CARRIER_FLAGS: ReadonlySet<string> = new Set([
  // Only flags that actually take a following value (readValue / readIntOption
  // callers) belong here. Boolean-only flags consumed via readFlag must be
  // excluded, otherwise the next positional would be swallowed as their value.
  "-b",
  "-m",
  "-q",
  "-t",
  "--additional-instructions",
  "--app",
  "--action",
  "--app-bundle",
  "--at",
  "--arg",
  "--arg-json",
  "--arg-value",
  "--arg-value-json",
  "--args-list-json",
  "--attempt",
  "--attempt-id",
  "--automation",
  "--autonomy",
  "--backend",
  "--base",
  "--base-branch",
  "--base-branch-ref",
  "--base-ref",
  "--body",
  "--branch",
  "--branch-name",
  "--branch-ref",
  "--bundle",
  "--bundle-id",
  "--category",
  "--color",
  "--cols",
  "--command",
  "--comment",
  "--comment-id",
  "--commit",
  "--compare-ref",
  "--caption",
  "--cdp-port",
  "--chat-session",
  "--chat-session-id",
  "--compare-to",
  "--content",
  "--context-file",
  "--cron",
  "--cwd",
  "--data",
  "--cpu",
  "--cpu-cores",
  "--debug-port",
  "--depth",
  "--desc",
  "--device",
  "--dispatch",
  "--dispatch-mode",
  "--disk",
  "--disk-size",
  "--display",
  "--duration",
  "--duration-ms",
  "--description",
  "--domain",
  "--droid-autonomy",
  "--droid-permission-mode",
  "--duration-sec",
  "--enabled",
  "--event",
  "--end-x",
  "--end-y",
  "--expected-head",
  "--expected-head-branch",
  "--delivery",
  "--file",
  "--for",
  "--fps",
  "--from",
  "--from-file",
  "--group",
  "--group-id",
  "--head",
  "--icon",
  "--id",
  "--image",
  "--image-url",
  "--in",
  "--index",
  "--initial-input",
  "--input",
  "--input-json",
  "--input-text",
  "--interval-ms",
  "--instructions",
  "--kind",
  "--json-input",
  "--lane",
  "--lane-id",
  "--limit",
  "--max-bytes",
  "--line",
  "--max-log-bytes",
  "--max-prompt-chars",
  "--max-rounds",
  "--memory",
  "--merge-method",
  "--message",
  "--method",
  "--mode",
  "--model",
  "--model-id",
  "--name",
  "--new",
  "--new-path",
  "--number",
  "--old",
  "--old-path",
  "--owner",
  "--owner-id",
  "--owner-kind",
  "--outcome",
  "--output",
  "--oid",
  "--params-json",
  "--parent",
  "--parent-lane",
  "--parent-lane-id",
  "--path",
  "--permission-mode",
  "--permissions",
  "--port",
  "--pr",
  "--pr-id",
  "--pr-number",
  "--pr-url",
  "--project",
  "--project-root",
  "--poll-interval-ms",
  "--prompt",
  "--provider",
  "--pty",
  "--pty-id",
  "--query",
  "--question",
  "--reason",
  "--reasoning",
  "--recovery-action",
  "--recent-limit",
  "--ref",
  "--require-dpop",
  "--role",
  "--root",
  "--root-lane",
  "--round",
  "--rounds",
  "--repo",
  "--repo-name",
  "--repo-owner",
  "--rows",
  "--rule",
  "--run",
  "--run-id",
  "--scalar",
  "--scalar-json",
  "--scope",
  "--seconds",
  "--session",
  "--session-id",
  "--set",
  "--set-json",
  "--sha",
  "--signal",
  "--since",
  "--source",
  "--source-lane",
  "--spawn-type",
  "--stack",
  "--stack-base",
  "--stack-base-branch",
  "--stack-id",
  "--scheme",
  "--socket",
  "--start-point",
  "--start-x",
  "--start-y",
  "--stash-oid",
  "--stash-ref",
  "--step",
  "--step-id",
  "--suite",
  "--suite-id",
  "--surface",
  "--state",
  "--tab",
  "--tab-identifier",
  "--task",
  "--task-id",
  "--target",
  "--target-id",
  "--terminal",
  "--terminal-id",
  "--thread",
  "--thread-id",
  "--turn",
  "--turn-id",
  "--timeout",
  "--timeout-ms",
  "--title",
  "--tool-type",
  "--title-query",
  "--type",
  "--udid",
  "--url",
  "--until",
  "--until-iso",
  "--value",
  "--window-title",
  "--workspace",
  "--workspace-id",
  "--workspace-root",
  "--coordinate-space",
  "--coords",
  "--x",
  "--xcodeproj",
  "--y",
]);

/**
 * The index of the first token that is a SUBCOMMAND rather than a flag's value.
 *
 * Taking the first token that does not start with a dash is the wrong answer:
 * in `--repo runs launch`, that token is `runs`, the VALUE of `--repo`. A
 * plugin alias that read it rerouted the command on someone's repository name
 * and then rewrote that value in place, so the command that ran was not the one
 * anybody typed.
 *
 * Stop at `--`, skip a flag, and skip the token after a flag that carries a
 * value — unless the value rode in the `--flag=value` form, which carries its
 * own. Returns -1 when there is no such token.
 */
export function firstStandalonePositionalIndex(args: readonly string[]): number {
  let previousTokenWasValueCarrier = false;
  for (let index = 0; index < args.length; index += 1) {
    const token = args[index]!;
    if (token === "--") return -1;
    if (previousTokenWasValueCarrier) {
      previousTokenWasValueCarrier = false;
      continue;
    }
    if (token.startsWith("-")) {
      const flagName = token.includes("=") ? token.slice(0, token.indexOf("=")) : token;
      previousTokenWasValueCarrier = !token.includes("=") && VALUE_CARRIER_FLAGS.has(flagName);
      continue;
    }
    return index;
  }
  return -1;
}

/** The word itself, lowercased by the caller when it matches against a table. */
export function firstStandalonePositionalWord(args: readonly string[]): string | null {
  const index = firstStandalonePositionalIndex(args);
  return index < 0 ? null : args[index]!;
}
