import type { ReviewEvidence, ReviewRunArtifact } from "../../../shared/types";

export type {
  ReviewAnchorState,
  ReviewArtifactType,
  ReviewCompareAgainstTarget,
  ReviewDiffContext,
  ReviewDismissReason,
  ReviewEvidence,
  ReviewEventPayload,
  ReviewFeedbackKind,
  ReviewFeedbackRecord,
  ReviewFinding,
  ReviewFindingAdjudication,
  ReviewFindingClass,
  ReviewFindingSuppressionMatch,
  ReviewLaunchCommit,
  ReviewLaunchContext,
  ReviewLaunchLane,
  ReviewListRunsArgs,
  ReviewListSuppressionsArgs,
  ReviewPassKey,
  ReviewPublication,
  ReviewPublicationDestination,
  ReviewPublicationInlineComment,
  ReviewPublicationState,
  ReviewPublicationStatus,
  ReviewPublishBehavior,
  ReviewQualityReport,
  ReviewRecordFeedbackArgs,
  ReviewResolvedCompareTarget,
  ReviewRun,
  ReviewRunArtifact,
  ReviewRunBudgetConfig,
  ReviewRunConfig,
  ReviewRunDetail,
  ReviewRunStatus,
  ReviewSelectionMode,
  ReviewSeverity,
  ReviewSeveritySummary,
  ReviewSourcePass,
  ReviewStartRunArgs,
  ReviewSuppression,
  ReviewSuppressionScope,
  ReviewTarget,
  ReviewTargetMode,
  ReviewToolSignalKind,
} from "../../../shared/types";

export type ReviewCompareKind = "default_branch" | "lane";
export type ReviewArtifact = ReviewRunArtifact;
export type ReviewEvidenceEntry = ReviewEvidence;
